<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Parallel Test Suite" duration-ms="30902" started-at="2021-09-07T02:57:51Z" finished-at="2021-09-07T02:58:22Z">
    <groups>
    </groups>
    <test name="OpenCartTest" duration-ms="28970" started-at="2021-09-07T02:57:51Z" finished-at="2021-09-07T02:58:20Z">
      <class name="suite1.OpenCartTests">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:suite1.OpenCartTests@340f438e]" name="beforeTest" is-config="true" duration-ms="3903" started-at="2021-09-06T21:57:51Z" finished-at="2021-09-06T21:57:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="launchSite()[pri:0, instance:suite1.OpenCartTests@340f438e]" name="launchSite" duration-ms="23360" started-at="2021-09-06T21:57:55Z" finished-at="2021-09-06T21:58:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchSite -->
        <test-method status="PASS" signature="searchForProduct()[pri:0, instance:suite1.OpenCartTests@340f438e]" name="searchForProduct" duration-ms="650" started-at="2021-09-06T21:58:18Z" finished-at="2021-09-06T21:58:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchForProduct -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:suite1.OpenCartTests@340f438e]" name="afterTest" is-config="true" duration-ms="1037" started-at="2021-09-06T21:58:19Z" finished-at="2021-09-06T21:58:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- suite1.OpenCartTests -->
    </test> <!-- OpenCartTest -->
    <test name="SaceDemoTest" duration-ms="30902" started-at="2021-09-07T02:57:51Z" finished-at="2021-09-07T02:58:22Z">
      <class name="suite2.SauceDemoTests">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:suite2.SauceDemoTests@1a407d53]" name="beforeTest" is-config="true" duration-ms="3903" started-at="2021-09-06T21:57:51Z" finished-at="2021-09-06T21:57:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="open()[pri:0, instance:suite2.SauceDemoTests@1a407d53]" name="open" duration-ms="22409" started-at="2021-09-06T21:57:55Z" finished-at="2021-09-06T21:58:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open -->
        <test-method status="FAIL" signature="login()[pri:1, instance:suite2.SauceDemoTests@1a407d53]" name="login" duration-ms="3435" started-at="2021-09-06T21:58:17Z" finished-at="2021-09-06T21:58:20Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at suite2.SauceDemoTests.login(SauceDemoTests.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:suite2.SauceDemoTests@1a407d53]" name="afterTest" is-config="true" duration-ms="1128" started-at="2021-09-06T21:58:20Z" finished-at="2021-09-06T21:58:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- suite2.SauceDemoTests -->
    </test> <!-- SaceDemoTest -->
  </suite> <!-- Parallel Test Suite -->
</testng-results>
